#/*
# * Copyright 2022 CoreLayer BV
# *
# *    Licensed under the Apache License, Version 2.0 (the "License");
# *    you may not use this file except in compliance with the License.
# *    You may obtain a copy of the License at
# *
# *        http://www.apache.org/licenses/LICENSE-2.0
# *
# *    Unless required by applicable law or agreed to in writing, software
# *    distributed under the License is distributed on an "AS IS" BASIS,
# *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# *    See the License for the specific language governing permissions and
# *    limitations under the License.
# */
name: stringmaps
tags:
sections:
  - name: appexpert.stringmaps
    elements:
      - name: ACME_CONFIG
        fields:
          - id: name
            data: <<prefix>>_ACME_CONFIG

          - id: key
            data: ("fqdn=" + HTTP.REQ.HOSTNAME + ";").SET_TEXT_MODE(NOIGNORECASE)
          - id: key_exists
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/key>>.IS_STRINGMAP_KEY("<<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/name>>")
          - id: value
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/key>>.MAP_STRING("<<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/name>>").TYPECAST_NVLIST_T(';','=')
          - id: value_is_cn
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value>>.VALUE("is_cn").SET_TEXT_MODE(NOIGNORECASE)
          - id: value_is_cn_true
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value_is_cn>>.EQ("true")
          - id: value_is_cn_false
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value_is_cn>>.EQ("false")
          - id: value_is_san_entry
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value>>.VALUE("is_san_domain").SET_TEXT_MODE(NOIGNORECASE)
          - id: value_is_san_entry_true
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value_is_san_entry>>.EQ("true")
          - id: value_is_san_entry_false
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value_is_san_entry>>.EQ("false")
          - id: value_san_parent_fqdn
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value>>.VALUE("san_parent_fqdn").SET_TEXT_MODE(NOIGNORECASE)
          - id: value_challenge_type
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value>>.VALUE("challenge_type").SET_TEXT_MODE(NOIGNORECASE)
          - id: value_challenge_type_is_http
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value_challenge_type>>.EQ("http")
          - id: value_challenge_type_is_dns
            data: <<core.stringmaps.appexpert.stringmaps.ACME_CONFIG/value_challenge_type>>.EQ("dns")
        expressions:
          install: add policy stringmap <<name>>
          uninstall: rm policy stringmap <<name>>